
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/provider/authProvider";
import ClientLayout from "@/components/client-layout";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className="bg-white">
        <AuthProvider>
          <ClientLayout>
          {children}
          </ClientLayout>
        </AuthProvider>
      </body>
    </html>
  );
}

